import os
import datetime
import torch
import numpy as np
import pandas as pd
from monty.serialization import dumpfn

# ASE Imports
from ase.io import write
from ase.optimize import LBFGS
from ase.filters import FrechetCellFilter
from ase.io.trajectory import Trajectory

# Pymatgen Imports
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.analysis.local_env import CrystalNN

# CHGNet Imports
from chgnet.model.model import CHGNet
from chgnet.model.dynamics import CHGNetCalculator

# --- 1. SETUP & RUN ID ---
RUN_ID = "perovskite_225_atoms"
CATIONS = ["Cu", "Ni", "Pd","Cr","Co"]
CATION_OXI = {"Cu": 2, "Ni": 2, "Co":2, "Pd":2, "Cr": 3}
ANION_OXI = {"O": -2}
FMAX_TOLERANCE = 0.05 #
TARGET_MOMS = {"Mn": 5.0, "Fe": 5.0, "Co": 3.0, "Ni": 2.0, "Cu": 1.0, "Cr": 3.0, "Mo": 0.0, "Ti": 0.0, "Pd": 0.0, "Ce": 0.0, "Zn": 0.0, "Mg": 0.0, "Zr": 0.0, "Al": 0.0}

current_dir = os.getcwd()
output_folder = os.path.join(current_dir, f"Results_{''.join(CATIONS)}_{RUN_ID}")
os.makedirs(output_folder, exist_ok=True)

# Input path (assuming generated by CIF_Generator.py)
CIF_INPUT = r"CODES\relaxation\used\start_CIFs\PdCuCoNiCrO_unrelaxed_perovskite_3x3x5.cif"

# --- 2. RELAXATION ---
print(f"--- Starting Production Run: {RUN_ID} ---")
model = CHGNet.load()
calc = CHGNetCalculator(model)
heo = Structure.from_file(CIF_INPUT)

adaptor = AseAtomsAdaptor()
atoms_heo = adaptor.get_atoms(heo)
atoms_heo.rattle(stdev=0.02)
atoms_heo.calc = calc

traj_file = os.path.join(output_folder, f"Relaxation_{RUN_ID}.traj")
opt = LBFGS(FrechetCellFilter(atoms_heo), trajectory=traj_file, logfile='-')
opt.run(fmax=FMAX_TOLERANCE)

# --- 3. POST-RELAXATION DATA EXTRACTION ---
relaxed_struct = adaptor.get_structure(atoms_heo)

# Critical: Assign oxidation states for CrystalNN accuracy
oxi_map = {**CATION_OXI, **ANION_OXI}
relaxed_struct.add_oxidation_state_by_element(oxi_map)

# Extract raw electronic data
moms_signed = atoms_heo.get_magnetic_moments()
moms_abs = np.abs(moms_signed)
forces = atoms_heo.get_forces()
total_energy = atoms_heo.get_potential_energy()

# --- 4. DESCRIPTOR LOOP ---
print("--- Calculating Multi-Property Descriptors ---")
cnn = CrystalNN()
sfi_all, ionicity_all, distortion_all = [], [], []
mean_bonds, min_bonds, max_bonds = [], [], []
neighbor_strings = []

for i, site in enumerate(relaxed_struct):
    symbol = site.specie.symbol
    
    # Get neighbors for structural/chemical metrics
    nb_info = cnn.get_nn_info(relaxed_struct, i)
    
    # Calculate actual bond distances
    bonds = [site.distance(nb['site']) for nb in nb_info]
    
    if symbol != "O":
        # Structural
        distortion_all.append(np.std(bonds) if bonds else 0)
        mean_bonds.append(np.mean(bonds) if bonds else 0)
        min_bonds.append(min(bonds) if bonds else 0)
        max_bonds.append(max(bonds) if bonds else 0)
        
        # Chemical Neighbors (Cation-only identity)
        cat_nbs = [nb['site'].specie.symbol for nb in nb_info if nb['site'].specie.symbol != "O"]
        neighbor_strings.append("-".join(sorted(cat_nbs)))
        
        # Electronic (SFI & Ionicity)
        m_target = TARGET_MOMS.get(symbol, 1.0)
        sfi = max(0, 1 - (abs(moms_abs[i] - m_target) / (m_target + 0.01)))
        sfi_all.append(sfi)
        ionicity_all.append(CATION_OXI[symbol] * sfi)
    else:
        # Fillers for Oxygen to keep array lengths consistent
        distortion_all.append(0); mean_bonds.append(0); min_bonds.append(0)
        max_bonds.append(0); neighbor_strings.append("Anion")
        sfi_all.append(0); ionicity_all.append(0)

# --- 5. STORE IN DIGITAL TWIN (JSON) ---
# Global Metadata
relaxed_struct.state = {
    "total_energy_eV": total_energy,
    "energy_per_atom": total_energy / len(relaxed_struct),
    "fmax_final": FMAX_TOLERANCE,
    "lattice_params": relaxed_struct.lattice.parameters,
    "volume": relaxed_struct.lattice.volume
}

# Site-Specific Arrays
relaxed_struct.add_site_property("magmom_signed", list(moms_signed))
relaxed_struct.add_site_property("magmom_abs", list(moms_abs))
relaxed_struct.add_site_property("force_vec", forces.tolist())
relaxed_struct.add_site_property("spin_fidelity", sfi_all)
relaxed_struct.add_site_property("ionicity_index", ionicity_all)
relaxed_struct.add_site_property("distortion_index", distortion_all)
relaxed_struct.add_site_property("bond_mean", mean_bonds)
relaxed_struct.add_site_property("bond_min", min_bonds)
relaxed_struct.add_site_property("bond_max", max_bonds)
relaxed_struct.add_site_property("neighbor_shell", neighbor_strings)

json_path = os.path.join(output_folder, f"DigitalTwin_{''.join(CATIONS)}.json")
dumpfn(relaxed_struct, json_path)

# --- 6. EXPORT SUMMARY CSV ---
summary = {
    "Run_ID": [RUN_ID],
    "E_Total": [total_energy],
    "E_Per_Atom": [total_energy / len(relaxed_struct)],
    "Mean_SFI": [np.mean([s for s in sfi_all if s > 0])],
    "Mean_Distortion": [np.mean([d for d in distortion_all if d > 0])]
}
pd.DataFrame(summary).to_csv(os.path.join(output_folder, "Summary.csv"), index=False)

relaxed_cif_path = os.path.join(output_folder, f"Relaxed_{''.join(CATIONS)}.cif")
relaxed_struct.to(filename=relaxed_cif_path)

# b. Extended XYZ for OVITO (Preserves all your site properties!)
atoms_export = adaptor.get_atoms(relaxed_struct)

# Add your new descriptors to the ASE arrays so they show up in OVITO
atoms_export.arrays["magmom"] = np.array(moms_signed)
atoms_export.arrays["spin_fidelity"] = np.array(sfi_all)
atoms_export.arrays["distortion"] = np.array(distortion_all)
atoms_export.arrays["ionicity"] = np.array(ionicity_all)

extxyz_path = os.path.join(output_folder, f"Relaxed_{''.join(CATIONS)}.extxyz")
write(extxyz_path, atoms_export)

print(f"\n--- SUCCESS ---")
print(f"Digital Twin saved with exhaustive descriptors: {json_path}")